# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\User\OneDrive - 國立成功大學 National Cheng Kung University\桌面\Hw1\HW1_VGG.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(248, 588)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 221, 491))
        self.groupBox.setObjectName("groupBox")
        self.q5_1 = QtWidgets.QPushButton(self.groupBox)
        self.q5_1.setGeometry(QtCore.QRect(20, 30, 171, 28))
        self.q5_1.setObjectName("q5_1")
        self.q5_2 = QtWidgets.QPushButton(self.groupBox)
        self.q5_2.setGeometry(QtCore.QRect(20, 110, 171, 28))
        self.q5_2.setObjectName("q5_2")
        self.q5_3 = QtWidgets.QPushButton(self.groupBox)
        self.q5_3.setGeometry(QtCore.QRect(20, 200, 171, 28))
        self.q5_3.setObjectName("q5_3")
        self.q5_4 = QtWidgets.QPushButton(self.groupBox)
        self.q5_4.setGeometry(QtCore.QRect(20, 290, 171, 28))
        self.q5_4.setObjectName("q5_4")
        self.q5_5 = QtWidgets.QPushButton(self.groupBox)
        self.q5_5.setGeometry(QtCore.QRect(20, 420, 171, 28))
        self.q5_5.setObjectName("q5_5")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(20, 390, 171, 22))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 248, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "VGG"))
        self.groupBox.setTitle(_translate("MainWindow", "VGG16 TEST"))
        self.q5_1.setText(_translate("MainWindow", "1. Show Train Image"))
        self.q5_2.setText(_translate("MainWindow", "2. Show HyperParameter"))
        self.q5_3.setText(_translate("MainWindow", "3. Show Model Shortcut"))
        self.q5_4.setText(_translate("MainWindow", "4. Show Accuracy"))
        self.q5_5.setText(_translate("MainWindow", "5. Test"))
